# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 17:08
from __future__ import unicode_literals
import csv

from django.db import migrations
from authentication.models import CountryCodes


def add_country_from_csv(apps, schema_editor):
    with open('country-codes.csv') as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            code = row['Dial']
            name = row['official_name_en']
            if code and name and code.isdigit():
                CountryCodes.objects.create(
                    name=name,
                    code=code
                )



def backward_migration(apps, schema_editor):
    """No backward migration needed."""
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_country_from_csv, backward_migration),
    ]
